dataset:
  ds_url: https://data.deepai.org/ptbdataset.zip
  ds_path: penn_treebank
  pad_value: 0

results: 
  logs_path: tmp

experiment:
  experiment_name: merity
  epochs: 50
  batch_size: 128
  model: merity
  optimizer: sgd
  learning_rate: 1e-1

model:
  embedding_dim: 400
  hidden_dim: 400
  num_layers: 3
  locked_dropout: True
  p_lockdrop: .1
  embedding_dropout: True
  p_embdrop: .1
  weight_dropout: True
  p_lstmdrop: .3
  p_hiddrop: .5
  init_weights: True
  tie_weights: True
