dataset:
  ds_url: https://data.deepai.org/ptbdataset.zip
  ds_path: penn_treebank
  pad_value: 0

results: 
  logs_path: runs
  results_path: results

experiment:
  seed: 42
  experiment_name: merity_ad_nohh_1024_adam
  epochs: 50
  batch_size: 128
  model: merity
  optimizer: adam
  learning_rate: 1e-3
  ntasgd: 3
  asgd_lr: 1
  gradient_clip_val: 0.25
  tbptt: False

model:
  embedding_dim: 1024
  hidden_dim: 1024
  num_layers: 2
  init_weights: True
  tie_weights: True
  locked_dropout: True
  p_lockdrop: .65
  embedding_dropout: True
  p_embdrop: .2
  weight_dropout: True
  p_lstmdrop: .4
  p_hiddrop: .0
