dataset:
  ds_url: https://data.deepai.org/ptbdataset.zip
  ds_path: penn_treebank
  pad_value: 0

results: 
  logs_path: runs
  results_path: results

experiment:
  seed: 42
  experiment_name: merity_ed
  epochs: 50
  batch_size: 128
  model: merity
  optimizer: sgd
  learning_rate: 1
  ntasgd: 3
  asgd_lr: 1
  gradient_clip_val: 0.25
  tbptt: False

model:
  embedding_dim: 400
  hidden_dim: 400
  num_layers: 3
  init_weights: True
  tie_weights: True
  locked_dropout: False
  p_lockdrop: .4
  embedding_dropout: True
  p_embdrop: .1
  weight_dropout: False
  p_lstmdrop: .3
  p_hiddrop: .5
